use serde::{Deserialize, Serialize};
use std::{fs, path::Path};

use crate::config::repo_config::RepoConfig;

#[derive(Serialize, Deserialize, Debug, Default)]
#[serde(rename_all = "kebab-case")]
pub struct MgitConfig {
    pub version: Option<String>,
    pub default_branch: Option<String>,
    pub default_remote: Option<String>,
    pub repos: Option<Vec<RepoConfig>>,
}

impl MgitConfig {
    pub fn load(path: impl AsRef<Path>) -> Option<Self> {
        if !path.as_ref().is_file() {
            return None;
        }

        let content = fs::read_to_string(path).unwrap().replace("\".\"", "\"\"");

        let Ok(mut toml_config) = toml::from_str::<MgitConfig>(&content) else {
            return None;
        };

        if let Some(item) = toml_config.repos.as_mut() {
            item.sort();
        }

        Some(toml_config)
    }

    pub fn serialize(&self) -> String {
        let toml_string = toml::to_string(self).unwrap_or_default();
        let mut out = String::new();

        out.push_str("# This file is automatically @generated by mgit.\n");
        out.push_str("# Editing it as you wish.\n");

        let Ok(doc) = toml_edit::ser::to_document(self) else {
            return toml_string;
        };

        let item = doc.as_item();

        let Some(table) = item.as_table() else {
            return toml_string;
        };

        if let Some(item) = table.get("version") {
            out.push_str(&format!("version = {}\n", item));
        }

        if let Some(item) = table.get("default-branch") {
            out.push_str(&format!("default-branch = {}\n", item));
        }

        if let Some(item) = table.get("default-remote") {
            out.push_str(&format!("default-remote = {}\n", item));
        }

        out.push('\n');

        if let Some(repos) = table.get("repos") {
            let list = repos.as_array().expect("repos must be an array");

            for entry in list {
                out.push_str("[[repos]]\n");
                let table = entry.as_inline_table().expect("repo must be table");

                if let Some(item) = table.get("local") {
                    out.push_str(&format!("local = {}\n", item));
                }

                if let Some(item) = table.get("remote") {
                    out.push_str(&format!("remote = {}\n", item));
                }

                if let Some(item) = table.get("branch") {
                    out.push_str(&format!("branch = {}\n", item));
                }

                if let Some(item) = table.get("tag") {
                    out.push_str(&format!("tag = {}\n", item));
                }

                if let Some(item) = table.get("commit") {
                    out.push_str(&format!("commit = {}\n", item));
                }

                if let Some(item) = table.get("sparse") {
                    out.push_str(&format!("sparse = {}\n", item));
                }

                if let Some(item) = table.get("labels") {
                    out.push_str(&format!("labels = {}\n", item));
                }

                out.push('\n');
            }
        }

        out
    }
}
