name: test-cli
on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  test_cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04,  windows-2022, macos-11]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.85.1
        override: true

    - name: run mgit test
      run: cargo test -p mgit
